name: Update Plugin Repository
on:
  push:
    paths:
      - 'listing.json'
  workflow_dispatch:
    inputs:
      message:
        description: 'automatically update readme and plugin.json based on updates and latest listing'
        required: true

jobs:
  run:
    name: Update Plugins.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Generator
        env:
          URL_SHORTENER: ${{ secrets.URL_SHORTENER }}
        run: python3 generate_index.py ${{ secrets.M_GITHUB_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: pluginmanager@vector35.com
          message: ${{ inputs.message }}
          add: '["*.json", "*.md"]'

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
