name: Validate New Plugin Repository
on:
  issues:
    types: [opened]
jobs:
  run:
    name: ValidateRepo 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Validator
        run: python3 validate_json.py ${{ secrets.M_GITHUB_TOKEN }}
        env:
          ISSUE_CONTENT: ${{ github.event.issue.body }}

      - name: Comment
        if: failure()
        uses: actions/github-script@v7
        with:
          #github-token: ${{secrets.M_GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Sorry, this repository does not appear to have a valid plugin.json.

              Please ensure it is valid JSON and that you have created an actual release.
              `
            })  

      - name: Report Status
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
